-- =====================================================
-- Queries de Monitoreo y Administración
-- Para el Sistema de Fusión de Datos con Background Jobs
-- =====================================================

-- =====================================================
-- 1. MONITOREO EN TIEMPO REAL
-- =====================================================

-- Ver todos los jobs activos con su progreso
SELECT 
  jp.JOB_ID,
  jp.PROGRESS_PCT || '%' AS PROGRESO,
  jp.STATUS_MESSAGE,
  jp.LAST_UPDATE,
  lf.ID_ARCHIVO,
  lf.TIPO_FUSION,
  lf.REGISTROS_PROCESADOS,
  lf.ESTADO,
  ROUND(EXTRACT(SECOND FROM (SYSTIMESTAMP - lf.FECHA_INICIO)) / 60, 2) AS MINUTOS_TRANSCURRIDOS,
  CASE 
    WHEN jp.PROGRESS_PCT > 0 THEN 
      ROUND((EXTRACT(SECOND FROM (SYSTIMESTAMP - lf.FECHA_INICIO)) / 60) * (100 / jp.PROGRESS_PCT), 1)
    ELSE NULL
  END AS TIEMPO_ESTIMADO_TOTAL_MIN
FROM SEGSOCIAL.JOB_PROGRESS jp
LEFT JOIN SEGSOCIAL.LOG_FUSION_DATOS lf ON jp.JOB_ID = lf.JOB_ID
WHERE lf.ESTADO IN ('INICIADO', 'EN_PROCESO')
  OR jp.LAST_UPDATE > SYSTIMESTAMP - INTERVAL '1' HOUR
ORDER BY jp.LAST_UPDATE DESC;

-- Ver el estado detallado de un job específico
SELECT SEGSOCIAL.FN_GET_FUSION_STATUS('TU_JOB_ID_AQUI') AS ESTADO FROM DUAL;

-- =====================================================
-- 2. HISTORIAL Y AUDITORÍA
-- =====================================================

-- Últimas 20 fusiones ejecutadas
SELECT 
  JOB_ID,
  ID_ARCHIVO,
  TIPO_FUSION,
  TO_CHAR(FECHA_INICIO, 'DD/MM/YYYY HH24:MI:SS') AS INICIO,
  TO_CHAR(FECHA_FIN, 'DD/MM/YYYY HH24:MI:SS') AS FIN,
  DURACION_SEGUNDOS,
  ROUND(DURACION_SEGUNDOS / 60, 2) AS DURACION_MINUTOS,
  REGISTROS_PROCESADOS,
  REGISTROS_FUSIONADOS,
  REGISTROS_ERRORES,
  ROUND((REGISTROS_FUSIONADOS / NULLIF(REGISTROS_PROCESADOS, 0)) * 100, 2) AS TASA_EXITO_PCT,
  ESTADO
FROM SEGSOCIAL.LOG_FUSION_DATOS
ORDER BY FECHA_INICIO DESC
FETCH FIRST 20 ROWS ONLY;

-- Fusiones del día actual
SELECT 
  JOB_ID,
  ID_ARCHIVO,
  TIPO_FUSION,
  TO_CHAR(FECHA_INICIO, 'HH24:MI:SS') AS HORA_INICIO,
  DURACION_SEGUNDOS,
  REGISTROS_PROCESADOS,
  REGISTROS_FUSIONADOS,
  ESTADO
FROM SEGSOCIAL.LOG_FUSION_DATOS
WHERE TRUNC(FECHA_INICIO) = TRUNC(SYSDATE)
ORDER BY FECHA_INICIO DESC;

-- Fusiones con errores en los últimos 7 días
SELECT 
  JOB_ID,
  ID_ARCHIVO,
  FECHA_INICIO,
  ERROR_MESSAGE,
REGISTROS_PROCESADOS,
  REGISTROS_ERRORES
FROM SEGSOCIAL.LOG_FUSION_DATOS
WHERE ESTADO = 'ERROR'
  AND FECHA_INICIO > SYSTIMESTAMP - INTERVAL '7' DAY
ORDER BY FECHA_INICIO DESC;

-- =====================================================
-- 3. ESTADÍSTICAS Y REPORTES
-- =====================================================

-- Resumen diario de fusiones
SELECT 
  TRUNC(FECHA_INICIO) AS FECHA,
  COUNT(*) AS TOTAL_FUSIONES,
  SUM(CASE WHEN ESTADO = 'COMPLETADO' THEN 1 ELSE 0 END) AS COMPLETADAS,
  SUM(CASE WHEN ESTADO = 'ERROR' THEN 1 ELSE 0 END) AS ERRORES,
  ROUND(AVG(DURACION_SEGUNDOS), 2) AS DURACION_PROMEDIO_SEG,
  SUM(REGISTROS_PROCESADOS) AS TOTAL_PROCESADOS,
SUM(REGISTROS_FUSIONADOS) AS TOTAL_FUSIONADOS,
  SUM(REGISTROS_ERRORES) AS TOTAL_ERRORES
FROM SEGSOCIAL.LOG_FUSION_DATOS
WHERE FECHA_INICIO > SYSTIMESTAMP - INTERVAL '30' DAY
GROUP BY TRUNC(FECHA_INICIO)
ORDER BY FECHA DESC;

-- Top 10 fusiones más lentas
SELECT 
  JOB_ID,
  ID_ARCHIVO,
  FECHA_INICIO,
  DURACION_SEGUNDOS,
  ROUND(DURACION_SEGUNDOS / 60, 2) AS DURACION_MINUTOS,
  REGISTROS_PROCESADOS,
  ROUND(REGISTROS_PROCESADOS / NULLIF(DURACION_SEGUNDOS, 0), 2) AS REGISTROS_POR_SEG,
  ESTADO
FROM SEGSOCIAL.LOG_FUSION_DATOS
WHERE ESTADO = 'COMPLETADO'
  AND FECHA_INICIO > SYSTIMESTAMP - INTERVAL '30' DAY
ORDER BY DURACION_SEGUNDOS DESC
FETCH FIRST 10 ROWS ONLY;

-- Performance por tipo de fusión
SELECT 
  TIPO_FUSION,
  COUNT(*) AS TOTAL_FUSIONES,
  ROUND(AVG(DURACION_SEGUNDOS), 2) AS DURACION_PROMEDIO_SEG,
  ROUND(AVG(REGISTROS_PROCESADOS), 0) AS REGISTROS_PROMEDIO,
  ROUND(AVG(REGISTROS_FUSIONADOS), 0) AS FUSIONADOS_PROMEDIO,
  ROUND(AVG(REGISTROS_ERRORES), 0) AS ERRORES_PROMEDIO,
  ROUND(AVG(REGISTROS_PROCESADOS / NULLIF(DURACION_SEGUNDOS, 0)), 2) AS THROUGHPUT_REG_SEG
FROM SEGSOCIAL.LOG_FUSION_DATOS
WHERE ESTADO = 'COMPLETADO'
AND FECHA_INICIO > SYSTIMESTAMP - INTERVAL '30' DAY
GROUP BY TIPO_FUSION
ORDER BY TIPO_FUSION;

-- =====================================================
-- 4. ANÁLISIS DE DATOS FUSIONADOS
-- =====================================================

-- Verificar registros fusionados por archivo
SELECT 
  ID_ARCHIVO,
  COUNT(*) AS TOTAL_REGISTROS,
  COUNT(DISTINCT CUIL) AS CUILS_UNICOS,
  SUM(REMUN1) AS TOTAL_REMUN1,
  SUM(REMUN2) AS TOTAL_REMUN2,
  SUM(REMUN3) AS TOTAL_REMUN3,
  MIN(FECHA_PROCESO) AS PRIMERA_FUSION,
  MAX(FECHA_PROCESO) AS ULTIMA_FUSION
FROM SEGSOCIAL.DATOS_FUSIONADOS
GROUP BY ID_ARCHIVO
ORDER BY ID_ARCHIVO DESC
FETCH FIRST 20 ROWS ONLY;

-- Buscar duplicados en datos fusionados (no debería haber)
SELECT 
  CUIL,
  ID_ARCHIVO,
  COUNT(*) AS OCURRENCIAS
FROM SEGSOCIAL.DATOS_FUSIONADOS
GROUP BY CUIL, ID_ARCHIVO
HAVING COUNT(*) > 1
ORDER BY OCURRENCIAS DESC;

-- Últimos registros fusionados
SELECT 
  ID,
  CUIL,
  APENOM,
  REMUN1,
  ID_ARCHIVO,
  TO_CHAR(FECHA_PROCESO, 'DD/MM/YYYY HH24:MI:SS') AS FECHA_PROCESO,
  JOB_ID
FROM SEGSOCIAL.DATOS_FUSIONADOS
ORDER BY ID DESC
FETCH FIRST 100 ROWS ONLY;

-- =====================================================
-- 5. MANTENIMIENTO Y LIMPIEZA
-- =====================================================

-- Ver tamaño de las tablas
SELECT 
  segment_name AS TABLA,
  ROUND(bytes / 1024 / 1024, 2) AS SIZE_MB,
  blocks AS BLOQUES,
  extents AS EXTENTS
FROM dba_segments
WHERE owner = 'SEGSOCIAL'
  AND segment_name IN ('JOB_PROGRESS', 'LOG_FUSION_DATOS', 'DATOS_FUSIONADOS')
ORDER BY bytes DESC;

-- Contar registros en cada tabla
SELECT 'JOB_PROGRESS' AS TABLA, COUNT(*) AS REGISTROS FROM SEGSOCIAL.JOB_PROGRESS
UNION ALL
SELECT 'LOG_FUSION_DATOS', COUNT(*) FROM SEGSOCIAL.LOG_FUSION_DATOS
UNION ALL
SELECT 'DATOS_FUSIONADOS', COUNT(*) FROM SEGSOCIAL.DATOS_FUSIONADOS;

-- Ver jobs progress antiguos (candidatos a limpieza)
SELECT 
  JOB_ID,
  PROGRESS_PCT,
  STATUS_MESSAGE,
  TO_CHAR(LAST_UPDATE, 'DD/MM/YYYY HH24:MI:SS') AS ULTIMA_ACTUALIZACION,
  ROUND(EXTRACT(DAY FROM (SYSTIMESTAMP - LAST_UPDATE)) + 
    EXTRACT(HOUR FROM (SYSTIMESTAMP - LAST_UPDATE)) / 24, 2) AS DIAS_ANTIGUEDAD
FROM SEGSOCIAL.JOB_PROGRESS
WHERE LAST_UPDATE < SYSTIMESTAMP - INTERVAL '1' DAY
ORDER BY LAST_UPDATE;

-- Ejecutar limpieza manual
BEGIN
  SEGSOCIAL.SP_LIMPIAR_FUSION_ANTIGUOS(p_dias_antiguedad => 30);
END;
/

-- Limpiar jobs progress huérfanos (sin registro en log)
DELETE FROM SEGSOCIAL.JOB_PROGRESS
WHERE LAST_UPDATE < SYSTIMESTAMP - INTERVAL '2' HOUR
  AND JOB_ID NOT IN (
  SELECT JOB_ID FROM SEGSOCIAL.LOG_FUSION_DATOS
    WHERE ESTADO IN ('INICIADO', 'EN_PROCESO')
  );
COMMIT;

-- =====================================================
-- 6. TROUBLESHOOTING
-- =====================================================

-- Detectar jobs colgados (más de 2 horas sin actualizar progreso)
SELECT 
  jp.JOB_ID,
  jp.PROGRESS_PCT,
  jp.STATUS_MESSAGE,
  jp.LAST_UPDATE,
  lf.ID_ARCHIVO,
  lf.FECHA_INICIO,
  ROUND(EXTRACT(HOUR FROM (SYSTIMESTAMP - jp.LAST_UPDATE)) + 
        EXTRACT(MINUTE FROM (SYSTIMESTAMP - jp.LAST_UPDATE)) / 60, 2) AS HORAS_SIN_ACTUALIZACION
FROM SEGSOCIAL.JOB_PROGRESS jp
LEFT JOIN SEGSOCIAL.LOG_FUSION_DATOS lf ON jp.JOB_ID = lf.JOB_ID
WHERE jp.LAST_UPDATE < SYSTIMESTAMP - INTERVAL '2' HOUR
  AND (lf.ESTADO IS NULL OR lf.ESTADO IN ('INICIADO', 'EN_PROCESO'))
ORDER BY jp.LAST_UPDATE;

-- Verificar jobs que no avanzaron en los últimos 15 minutos
SELECT 
  jp.JOB_ID,
  jp.PROGRESS_PCT,
  jp.LAST_UPDATE,
  lf.ESTADO
FROM SEGSOCIAL.JOB_PROGRESS jp
LEFT JOIN SEGSOCIAL.LOG_FUSION_DATOS lf ON jp.JOB_ID = lf.JOB_ID
WHERE jp.LAST_UPDATE BETWEEN SYSTIMESTAMP - INTERVAL '30' MINUTE 
        AND SYSTIMESTAMP - INTERVAL '15' MINUTE
  AND jp.PROGRESS_PCT < 100
  AND jp.PROGRESS_PCT >= 0;

-- Ver errores de Oracle en fusiones
SELECT 
  JOB_ID,
  ID_ARCHIVO,
  FECHA_INICIO,
  FECHA_FIN,
  ERROR_MESSAGE
FROM SEGSOCIAL.LOG_FUSION_DATOS
WHERE ERROR_MESSAGE IS NOT NULL
ORDER BY FECHA_INICIO DESC
FETCH FIRST 20 ROWS ONLY;

-- Buscar patrones de errores
SELECT 
  SUBSTR(ERROR_MESSAGE, 1, 100) AS ERROR_PATRON,
  COUNT(*) AS OCURRENCIAS,
  MIN(FECHA_INICIO) AS PRIMER_ERROR,
  MAX(FECHA_INICIO) AS ULTIMO_ERROR
FROM SEGSOCIAL.LOG_FUSION_DATOS
WHERE ERROR_MESSAGE IS NOT NULL
GROUP BY SUBSTR(ERROR_MESSAGE, 1, 100)
ORDER BY OCURRENCIAS DESC;

-- =====================================================
-- 7. COMANDOS ÚTILES DE ADMINISTRACIÓN
-- =====================================================

-- Forzar finalización de un job (usar con precaución)
UPDATE SEGSOCIAL.JOB_PROGRESS 
SET PROGRESS_PCT = -1, 
    STATUS_MESSAGE = 'Finalizado manualmente por administrador',
    LAST_UPDATE = SYSTIMESTAMP
WHERE JOB_ID = 'TU_JOB_ID_AQUI';
COMMIT;

-- Marcar fusión como ERROR (si el job murió sin registrar estado final)
UPDATE SEGSOCIAL.LOG_FUSION_DATOS
SET ESTADO = 'ERROR',
    FECHA_FIN = SYSTIMESTAMP,
    ERROR_MESSAGE = 'Proceso interrumpido - Terminado manualmente',
    DURACION_SEGUNDOS = EXTRACT(SECOND FROM (SYSTIMESTAMP - FECHA_INICIO)) +
            EXTRACT(MINUTE FROM (SYSTIMESTAMP - FECHA_INICIO)) * 60
WHERE JOB_ID = 'TU_JOB_ID_AQUI'
  AND ESTADO IN ('INICIADO', 'EN_PROCESO');
COMMIT;

-- Recrear índices (si performance degradada)
ALTER INDEX IDX_LOG_FUSION_JOB REBUILD;
ALTER INDEX IDX_LOG_FUSION_ARCHIVO REBUILD;
ALTER INDEX IDX_LOG_FUSION_FECHA REBUILD;
ALTER INDEX IDX_DATOS_FUSION_CUIL REBUILD;
ALTER INDEX IDX_DATOS_FUSION_ARCHIVO REBUILD;

-- Actualizar estadísticas de las tablas
BEGIN
  DBMS_STATS.GATHER_TABLE_STATS('SEGSOCIAL', 'JOB_PROGRESS');
  DBMS_STATS.GATHER_TABLE_STATS('SEGSOCIAL', 'LOG_FUSION_DATOS');
  DBMS_STATS.GATHER_TABLE_STATS('SEGSOCIAL', 'DATOS_FUSIONADOS');
END;
/

-- =====================================================
-- 8. VALIDACIONES DE INTEGRIDAD
-- =====================================================

-- Verificar que todos los jobs en log tienen su entrada en progress (para jobs activos)
SELECT 
  lf.JOB_ID,
  lf.ESTADO,
  lf.FECHA_INICIO,
  CASE WHEN jp.JOB_ID IS NULL THEN 'FALTA PROGRESS' ELSE 'OK' END AS ESTADO_PROGRESS
FROM SEGSOCIAL.LOG_FUSION_DATOS lf
LEFT JOIN SEGSOCIAL.JOB_PROGRESS jp ON lf.JOB_ID = jp.JOB_ID
WHERE lf.ESTADO IN ('INICIADO', 'EN_PROCESO')
  AND lf.FECHA_INICIO > SYSTIMESTAMP - INTERVAL '1' DAY;

-- Verificar consistencia entre registros procesados y datos fusionados
SELECT 
  lf.JOB_ID,
  lf.ID_ARCHIVO,
  lf.REGISTROS_PROCESADOS AS PROCESADOS_LOG,
  lf.REGISTROS_FUSIONADOS AS FUSIONADOS_LOG,
  COUNT(df.ID) AS REGISTROS_EN_TABLA,
  CASE 
    WHEN COUNT(df.ID) = lf.REGISTROS_FUSIONADOS THEN 'OK'
    ELSE 'INCONSISTENCIA'
  END AS ESTADO_CONSISTENCIA
FROM SEGSOCIAL.LOG_FUSION_DATOS lf
LEFT JOIN SEGSOCIAL.DATOS_FUSIONADOS df ON lf.ID_ARCHIVO = df.ID_ARCHIVO AND lf.JOB_ID = df.JOB_ID
WHERE lf.ESTADO = 'COMPLETADO'
  AND lf.FECHA_INICIO > SYSTIMESTAMP - INTERVAL '7' DAY
GROUP BY lf.JOB_ID, lf.ID_ARCHIVO, lf.REGISTROS_PROCESADOS, lf.REGISTROS_FUSIONADOS
HAVING COUNT(df.ID) != lf.REGISTROS_FUSIONADOS
ORDER BY lf.FECHA_INICIO DESC;
